name: responsive_design
description: Create responsive applications using different widgets that adapt to different screen densities.
version: 0.0.13
repository: https://github.com/astudilloalex/flutter_responsive_design/tree/stable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/lint
  lint: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: