name: responsive_design
description: Create responsive applications using different widgets that adapt to different screen densities.
version: 0.0.21
repository: https://github.com/astudilloalex/flutter_responsive_design/tree/stable

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/lint
  lint: ^1.8.2

flutter: